### ISSUE TITLE
Working Methodologies Slide Deck

### ISSUE THREAD

**Issue by mdodell** [TAMID-Tech-Consulting/education-resources#11]
# Purpose
There exists a slide deck that explains working methodologies in the tech world
# What should the slide deck contain?
* What is Scrum, AGILE, Waterfall?
* Advantages/Disadvantages of each
* Example of what they look like in real-world settings

**Comment by harhur** [comment]
https://docs.google.com/presentation/d/1WHB04i4_8gKCalQWHdJ-igRFM-rnHpfA-IWEXDE8Iyg/edit?usp=sharing
