### ISSUE TITLE
What are APIs?

### ISSUE THREAD

**Issue by jlevine272** [TAMID-Tech-Consulting/education-resources#13]
# Purpose
There exists a slide deck that explains what APIs are.
# What should the slide deck contain?

- How do APIs work?
- How can I find APIs?
- Why are APIs  #necessary?
- Examples of APIs
- Using SDKs

**Comment by mdodell** [comment]
@jlevine272 AWESOME JOB! I had a few comments/technical nitpicks. Seriously great work, I loved the exercise. I thought this was super well-done. Can you ping me with your comments/let me know if I should re-review?
