### ISSUE TITLE
Troubleshooting Your Code

### ISSUE THREAD

**Issue by jlevine272** [TAMID-Tech-Consulting/education-resources#16]
# Purpose
There exists a slide deck about troubleshooting code.
# What should the slide deck contain?

- What to do when you get stuck
- Resources to get advice
- Understanding documentation

**Comment by mdodell** [comment]
@jlevine272 Wrote some comments on this slide deck. I had some ideas of extra things you could incorporate in regards to a potential exercise or more resources. Again, keep up the great work!
