### ISSUE TITLE
Terminology used in the software world

### ISSUE THREAD

**Issue by mdodell** [TAMID-Tech-Consulting/education-resources#9]
# Purpose
There exists a slide deck that explains common technology terms that one may hear in the tech world
# What should the slide deck contain?
* What is front-end, back-end, full-stack, DevOps, UI/UX Design, etc (brief overviews of all of these topics)
* What is SCRUM, AGILE (brief overview)?
* What are balanced teams?

**Comment by harhur** [comment]
https://docs.google.com/presentation/d/1Fn_7W0lSV3TYLDNCxIRvTeZyLVvlRoW_SwjjP0VrIkc/edit?usp=sharing

**Comment by mdodell** [comment]
@harhur Left a comment on the slides!

**Comment by harhur** [comment]
thanks!
